# Intro to Machine Learning

[Course Link](https://www.kaggle.com/learn/intro-to-machine-learning)

In [33]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [4]:
CWD = os.getcwd()
DATA = CWD + '/tutorials_data/'

MELB = DATA + 'housing_melbourne.csv'
TRAIN = DATA + 'housing_train.csv'

## 1. Decision trees

A simple decision tree asks if a house has more than 2 bedrooms, and whether this affects price with 'No' predicting a lower price.

This divides houses into two categories, and then the price of that group is determined by the historical average of all houses in that group.

This simple decision tree doesn't capture any other factors e.g. number of bathrooms, location etc.

More factors can be captured using a tree with more splits, called 'deeper' trees.

Each factor provides another layer of the decision tree, and the bottom layer where a prediction is made is called a 'leaf'.

## 2. Exploring the data

In [5]:
# Import
df_melb = pd.read_csv(MELB)
# Show data
df_melb.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [6]:
# Describe data
df_melb.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [7]:
# Import data
df_train = pd.read_csv(TRAIN)
# Show data
df_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [8]:
# Describe data
df_train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

## 3. Building the model

Datasets may come with a high number of features, and need to be reduced for better understanding.

In [9]:
# Show columns
df_melb.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

Missing data may also need to be handled, for now, all rows with missing data will be dropped.

In [10]:
# Drop missing data
df_melb = df_melb.dropna(axis = 0)

### Selecting prediction target

By convention the prediction target is called `y`, and is extracted below

In [17]:
y = df_melb['Price']

### Feature selection

In [18]:
# Define features
list_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']
# Set features
X = df_melb[list_features]
# Show data
X.head()

   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954

In [19]:
# Describe data
X.describe()

             Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  6196.000000  6196.000000   6196.000000  6196.000000  6196.000000
mean      2.931407     1.576340    471.006940   -37.807904   144.990201
std       0.971079     0.711362    897.449881     0.075850     0.099165
min       1.000000     1.000000      0.000000   -38.164920   144.542370
25%       2.000000     1.000000    152.000000   -37.855438   144.926198
50%       3.000000     1.000000    373.000000   -37.802250   144.995800
75%       4.000000     2.000000    628.000000   -37.758200   145.052700
max       8.000000     8.000000  37000.000000   -37.457090   145.526350

### Defining the model

In [20]:
# Define model
model = DecisionTreeRegressor(random_state = 1)
# Fit model
model.fit(X, y)

DecisionTreeRegressor(random_state=1)

In [ ]:
# Generate predictions for subset of data
y_pred = model.predict(X.head())
# Show data
y_pred

array([1035000., 1465000., 1600000., 1876000., 1636000.])

## 4. Model validation

### Mean Absolute Error

In most applications, the relevant measure of model quality is predictive accuracy.

Often, the mistake is made where predictions are made using training data, and compared to real values in the training data.

First, model quality must be summarised into an interpretable metric. We will use the **Mean Absolute Error (MAE)**.

Here, the absolute value of each error i.e. $error = actual - predicted$, is calculated and the average of all absolute error values taken.

'On average, the predictions made differ from real values by X amount.'

In [26]:
# Import data
df_melb = pd.read_csv(MELB)
# Drop NaN
df_melb = df_melb.dropna(axis = 0)
# Define features
list_features = ['Rooms', 'Bathroom', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude']
# Define predictor
y = df_melb['Price']
# Define features
X = df_melb[list_features]

# Define model
model = DecisionTreeRegressor(random_state = 1)
# Fit data
model.fit(X, y)
# Predict values
y_pred = model.predict(X)
# Calculate MAE
mean_absolute_error(y, y_pred)

434.71594577146544

### Validation data

In the above example, a single sample of houses was used for building and evaluating the model.

This may accidentally capture some random association between the predicted value and some feature in the single sample, that is not generalisable .

A model's value comes from making predictions on new data, and so performance must be measured on data **not used** to build the model i.e. validation data.

In [28]:
# Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state = 0)
# Define model
model = DecisionTreeRegressor()
# Fit model
model.fit(X_train, y_train)
# Generate predictions based on validation data
y_pred = model.predict(X_val)
# Calculate MAE
mean_absolute_error(y_val, y_pred)

266024.70755326014

This shows a massive discrepancy between the in-sample and out-sample MAE (~$430 to ~$266k).

## 5. Underfitting and overfitting

The `DecisionTreeRegressor()` model has many options, but the most important is the depth.

It is not uncommon to have trees with 10 splits between the top level and a leaf.

More splits leads to smaller numbers of houses in each leaf. These will produce accurate predictions for those houses, but may be unreliable for new data. 

This is called **overfitting* where a model matches training data closely but generalises poorly.

On the other hand, if the tree is too shallow to split data into meaningful groups, prediction accuracy will be low even within the training data, and further on new data. This is called **underfitting**.

### Controlling tree depth

`max_leaf_nodes` provides a way to control over/underfitting. The more leaves, the more likely overfitting occurs.

A utility function can be defined to compare MAE scores from different values for `max_leaf_nodes`.

In [29]:
# Define function
def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    # Define model
    model = DecisionTreeRegressor(max_leaf_nodes = max_leaf_nodes, random_state = 0)
    # Fit model
    model.fit(train_X, train_y)
    # Generate predictions
    preds_val = model.predict(val_X)
    # Calculate MAE
    mae = mean_absolute_error(val_y, preds_val)
    
    return mae

In [32]:
# Define leaf node numbers
list_max_leaves = [5, 50, 500, 5000]

# Iterate over leaf number
for max_leaf_nodes in list_max_leaves:
    # Calculate mae
    mae = get_mae(max_leaf_nodes, X_train, X_val, y_train, y_val)
    # Report
    print(f'Max leaf nodes: {max_leaf_nodes} \t \t Mean Absolute Error: {mae}')

Max leaf nodes: 5 	 	 Mean Absolute Error: 347380.33833344496
Max leaf nodes: 50 	 	 Mean Absolute Error: 258171.21202406782
Max leaf nodes: 500 	 	 Mean Absolute Error: 243495.96361790417
Max leaf nodes: 5000 	 	 Mean Absolute Error: 255575.12911555843

Here, 500 is shown to be the optimal leaf number, given the lowest MAE.

## 6. Random forests

Decision trees face a lot of over/underfitting problems.

Random forest uses many trees, and averages the predictions of each tree to generate a prediction. 

This generally has a much better predictive accuracy than a single tree, and works well with default parameters.

More complex models can produce better predictions, but rely heavily on parameter testing.

In [34]:
# Define model
model = RandomForestRegressor(random_state = 1)
# Fit model
model.fit(X_train, y_train)
# Generate predictions
y_pred = model.predict(X_val)
# Calculate MAE
mean_absolute_error(y_val, y_pred)

191669.7536453626

This MAE improves over the single decision tree of ~$266k.